import { join } from 'node:path';

import { defineConfig } from 'vitest/config';

/**
 * The substrate's own test configuration.
 *
 * `root` is pinned to this directory so the run does not pick up the repository's
 * `vitest.config.ts`, which carries `fileParallelism: false` and a `globalSetup` that
 * belong to jen's own suite and not to this one.
 *
 * Pinning `root` moves the cache with it, and the default would put it at
 * `agent/node_modules/.vite` — untracked, regenerated by every run, and not covered by the
 * repository's `/node_modules/` rule, which is anchored to the root. It is sent to the
 * repository's own `node_modules` instead. Ignoring it where it fell would have meant
 * editing the root `.gitignore`, which `agent-substrate` requires this change to leave
 * alone, to hide an artifact that did not need to exist.
 *
 * The timeout is long because every test here drives a real container runtime: the first
 * run pulls an image, and the leak test cycles create/destroy a few dozen times.
 */
export default defineConfig({
  cacheDir: join(import.meta.dirname, '..', 'node_modules', '.vite', 'agent'),
  test: {
    root: import.meta.dirname,
    include: ['**/*.test.ts'],
    testTimeout: 300_000,
    hookTimeout: 300_000,
  },
});
